version: "3"
services:
  frontend:
    image: ecofreshkaese/medals-frontend:latest
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "1024:80"
    depends_on:
      - backend
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  backend:
    image: ecofreshkaese/medals-backend:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --label-enable --cleanup
