services:
  frontend:
    image: medals-frontend-dev:latest
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "1024:80"
    depends_on:
      - backend
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  backend:
    image: medals-backend-dev:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - postgres_db
    environment:
      - SPRING_PROFILES_ACTIVE=production
    env_file:
      - deploy.env

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --label-enable --cleanup

  postgres_db:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - medals_postgres_data:/var/lib/postgresql/data
    env_file:
      - deploy.env

  db_backup:
    build:
      context: ./db_backup
      dockerfile: db-backup.Dockerfile
    volumes:
      - medals_postgres_data:/var/lib/postgresql/data
      - medals_db_backup:/backups
    depends_on:
      - postgres_db
    env_file:
      - deploy.env

volumes:
  medals_postgres_data:
    name: medals_postgres_data
  medals_db_backup:
    name: medals_db_backup
