services:
  frontend:
    image: ecofreshkaese/medals-frontend:latest
    ports:
      - "1024:80"
    depends_on:
      - backend
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  backend:
    image: ecofreshkaese/medals-backend:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - postgres_db
    environment:
      - SPRING_PROFILES_ACTIVE=production
    env_file:
      - deploy.env
    volumes:
      - ./backend/application-production.yaml:/config/application-production.yaml

  watchtower:
    image: containrrr/watchtower@sha256:f772af6854833009c203b1f5d816714b307213989cdfdc0a1797a9e60e5f6cc7
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --label-enable --cleanup

  postgres_db:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - db_backup:/backups
      - ./scripts/dbBackup.sh:/dbBackup.sh
    env_file:
      - deploy.env

volumes:
  postgres_data:
    name: medals_postgres_data
  db_backup:
    name: medals_db_backup
