version: "3"
services:
  frontend:
    image: ecofreshkaese/medals-frontend:latest
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "1024:80"
    depends_on:
      - backend
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  backend:
    image: ecofreshkaese/medals-backend:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - postgres_db

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --label-enable --cleanup

  postgres_db:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - medals_postgres_data:/var/lib/postgresql/data
    env_file:
      - deploy.env

volumes:
  medals_postgres_data:
    name: medals_postgres_data
