services:
  frontend:
    image: ecofreshkaese/medals-frontend:latest
    ports:
      - "80:80"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - backend

  backend:
    image: ecofreshkaese/medals-backend:latest
