services:
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "81:80"
    depends_on:
      - backend

  backend:
    image: ecofreshkaese/medals-backend:latest
