#!/bin/bash

git clone https://github.com/Magenta-Mause/Medals-Deployment.git
cd Medals-Deployment

EMAIL_AUTHOR="noreply@medals.com"
JWS_SECRET=$(LC_ALL=C < /dev/urandom tr -dc 'a-z0-9' | head -c 512)

if [ -f deploy.env ]; then
    echo "deploy.env already exists. Overwrite? (y/n)"
    read OVERWRITE
    if [ "$OVERWRITE" != "y" ]; then
        echo "Aborting installation."
        exit 1
    fi
fi

echo "Please enter your email address:"
read USER_EMAIL_ADDRESS

echo "Please enter your first name:"
read FIRST_NAME

echo "Please enter your last name:"
read LAST_NAME

echo "Please enter a database password:"
read -s POSTGRES_PASSWORD
echo

echo "# This file was generated by the installation script.
POSTGRES_USER=root
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=medals
JWS_SECRET=$JWS_SECRET
EMAIL_ENDPOINT=https://projektejwkk.de/_____mailGen
EMAIL_AUTHOR=$EMAIL_AUTHOR
APP_ADMIN_ADMINS_0_EMAIL=$USER_EMAIL_ADDRESS
APP_ADMIN_ADMINS_0_FIRST-NAME=$FIRST_NAME
APP_ADMIN_ADMINS_0_LAST-NAME=$LAST_NAME

" > deploy.env

docker compose -f compose-local.yaml up
echo "You should be able to reach the medals-frontend under http://localhost:1024"
