#!/bin/bash

EMAIL_AUTHOR="noreply@medals.com"
JWS_SECRET=$(tr -dc 'a-z0-9' < /dev/urandom | head -c 512)

echo "Please enter your email address:"
read USER_EMAIL_ADDRESS

echo "Please enter your first name:"
read FIRST_NAME

echo "Please enter your last name:"
read LAST_NAME

echo "Please enter a database password:"
read POSTGRES_PASSWORD

echo "# This file was generated by the installation script.
POSTGRES_USER=root
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=medals
JWS_SECRET=$JWS_SECRET
EMAIL_ENDPOINT=https://projektejwkk.de/_____mailGen
EMAIL_AUTHOR=$EMAIL_AUTHOR
APP_ADMIN_ADMINS_0_EMAIL=$USER_EMAIL_ADDRESS
APP_ADMIN_ADMINS_0_FIRST-NAME=$FIRST_NAME
APP_ADMIN_ADMINS_0_LAST-NAME=$LAST_NAME

" > deploy.env

docker compose -f compose-local.yaml up
