spring:
  application:
    name: Medals-Backend
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.thymeleaf.ThymeleafAutoConfiguration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://postgres_db:5432/medals
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
cors:
  allowedOrigins:
    - http://localhost:5173
    - http://192.168.178.21:5173
    - http://localhost:3000
    - https://stratssync.com
    - http://localhost:1024
app:
  admin:
    enabled: true
    admins: # Change your admins here
      - email: ${ALEXANDER_EMAIL}
        first-name: "EcoFresh"
        last-name: "Kase"
      - email: ${JANNE_EMAIL}
        first-name: "Janne"
        last-name: "6565"
      - email: ${PY_BAY_EMAIL}
        first-name: "Py"
        last-name: "Bay"
      - email: ${HYUNJOON_EMAIL}
        first-name: "Joon"
        last-name: "Jester"
      - email: ${FIETE_MINGE_EMAIL}
        first-name: "Fiete"
        last-name: "Nsen"
      - email: ${LARSBOBO_EMAIL}
        first-name: "Lars"
        last-name: "Bobo"
      - email: ${MCLEMURI_EMAIL}
        first-name: "MC"
        last-name: "Lemuri"
      - email: ${LEESOKO_EMAIL}
        first-name: "Lee"
        last-name: "Soko"
  security:
    identity-token-expiration-time: 3600000
    refresh-token-expiration-time: 2678400000
    secret-key: ${JWS_SECRET}
  email:
    url: ${EMAIL_ENDPOINT}
    author: ${EMAIL_AUTHOR}
    templates:
      set-password-notification: "template_account_created"
      invite-trainer-notification: "template_trainer_invitation"
      reset-password-notification: "template_reset_password"
      password-reset-notification: "template_password_reset"
  notification:
    front-end-base-url: https://stratssync.com # add your base url here
  otc:
    set-password-token-validity-duration: 604800000
    reset-password-token-validity-duration: 3600000
