name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Deployment
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.MEDALS_DEPLOYMENT_HOST }}
          username: ${{ secrets.MEDALS_DEPLOYMENT_USERNAME }}
          key: ${{ secrets.MEDALS_DEPLOYMENT_SSH_TOKEN }}
          port: ${{ secrets.MEDALS_DEPLOYMENT_PORT }}
          script: sudo systemctl start medals-get-deployment.service
